package com.bobfull.chat.service;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.BDDMockito.*;
import com.bobfull.chat.entity.*; import com.bobfull.chat.port.*; import com.bobfull.chat.repository.*; import com.bobfull.common.exception.*; import com.bobfull.common.security.*; import com.bobfull.reservation.entity.*; import java.time.Clock; import java.time.Instant; import java.time.ZoneOffset; import java.util.*; import org.junit.jupiter.api.Test; import org.springframework.test.util.ReflectionTestUtils;
class ChatMessageCommandServiceTest {
    private static final Instant NOW = Instant.parse("2026-08-06T00:00:00Z");
    private final ChatRoomRepository rooms=org.mockito.Mockito.mock(ChatRoomRepository.class); private final ChatMessageRepository messages=org.mockito.Mockito.mock(ChatMessageRepository.class); private final ReservationChatAccessReader access=org.mockito.Mockito.mock(ReservationChatAccessReader.class); private final MemberNameReader names=org.mockito.Mockito.mock(MemberNameReader.class); private final Clock clock=Clock.fixed(NOW, ZoneOffset.UTC);
    private final com.bobfull.outbox.repository.OutboxEventRepository outboxEvents=org.mockito.Mockito.mock(com.bobfull.outbox.repository.OutboxEventRepository.class); private final com.bobfull.outbox.service.ChatMessageOutboxSignalDispatcher outboxSignalDispatcher=org.mockito.Mockito.mock(com.bobfull.outbox.service.ChatMessageOutboxSignalDispatcher.class);
    private final com.bobfull.chat.infrastructure.redis.RedisChatMessagePublisher realtimePublisher=org.mockito.Mockito.mock(com.bobfull.chat.infrastructure.redis.RedisChatMessagePublisher.class);
    private final ChatMessageCommandService service=new ChatMessageCommandService(rooms,messages,access,names,clock,outboxEvents,outboxSignalDispatcher,realtimePublisher);
    { given(outboxEvents.save(any())).willAnswer(invocation -> { com.bobfull.outbox.entity.OutboxEvent event=invocation.getArgument(0); ReflectionTestUtils.setField(event,"id",501L); return event; }); }
    @Test void Principal_회원과_참여자_ID로_메시지를_저장한다(){ ChatRoom room=room(); ChatMessage saved=ChatMessage.create(3L,7L,8L,"안녕하세요"); ReflectionTestUtils.setField(saved,"id",101L); ReflectionTestUtils.setField(saved,"createdAt", Instant.parse("2026-08-06T00:00:00Z")); given(rooms.findById(3L)).willReturn(Optional.of(room)); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.RECRUITING)); given(messages.save(any())).willReturn(saved); given(names.readNames(any())).willReturn(Map.of(7L,"회원")); var response=service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"안녕하세요"); assertThat(response).extracting("messageId","senderMemberId","senderParticipantId","content").containsExactly(101L,7L,8L,"안녕하세요"); }
    @Test void 빈공백과_1001자_메시지는_저장전에_차단한다(){ assertInvalid(null);assertInvalid("");assertInvalid("   ");assertInvalid("a".repeat(1001)); }
    @Test void CANCELLED와_전송불가_예약상태는_차단한다(){ given(rooms.findById(3L)).willReturn(Optional.of(room())); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.CANCELLED,ReservationStatus.RECRUITING)); assertCode(() -> service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"a"),CommonErrorCode.ACCESS_DENIED); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.CANCELLING)); assertCode(() -> service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"a"),ChatErrorCode.CHAT_MESSAGE_SEND_NOT_ALLOWED); verify(messages,never()).save(any()); verify(outboxEvents,never()).save(any()); }
    @Test void 메시지_저장에_성공하면_같은_트랜잭션에서_CHAT_MESSAGE_CREATED_Outbox를_저장하고_커밋후_signal과_Redis_전파를_디스패치한다(){ ChatRoom room=room(); ChatMessage saved=ChatMessage.create(3L,7L,8L,"안녕하세요"); ReflectionTestUtils.setField(saved,"id",101L); ReflectionTestUtils.setField(saved,"createdAt",NOW); given(rooms.findById(3L)).willReturn(Optional.of(room)); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.RECRUITING)); given(messages.save(any())).willReturn(saved); given(names.readNames(any())).willReturn(Map.of(7L,"회원")); service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"안녕하세요"); org.mockito.ArgumentCaptor<com.bobfull.outbox.entity.OutboxEvent> captor=org.mockito.ArgumentCaptor.forClass(com.bobfull.outbox.entity.OutboxEvent.class); verify(outboxEvents).save(captor.capture()); assertThat(captor.getValue()).extracting("eventType","aggregateId").containsExactly(com.bobfull.outbox.entity.OutboxEventType.CHAT_MESSAGE_CREATED,101L); verify(outboxSignalDispatcher).dispatch(501L); verify(realtimePublisher).publish(new com.bobfull.chat.dto.ChatMessageSentResponse(101L,3L,7L,8L,"회원","안녕하세요",NOW)); }
    @Test void 트랜잭션_커밋_전에는_Redis_전파하지_않고_커밋후에만_전파한다(){ ChatMessage saved=ChatMessage.create(3L,7L,8L,"안녕하세요"); ReflectionTestUtils.setField(saved,"id",101L); ReflectionTestUtils.setField(saved,"createdAt",NOW); given(rooms.findById(3L)).willReturn(Optional.of(room())); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.RECRUITING)); given(messages.save(any())).willReturn(saved); given(names.readNames(any())).willReturn(Map.of(7L,"회원")); org.springframework.transaction.support.TransactionSynchronizationManager.initSynchronization(); try { service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"안녕하세요"); verifyNoInteractions(realtimePublisher); org.springframework.transaction.support.TransactionSynchronizationManager.getSynchronizations().forEach(org.springframework.transaction.support.TransactionSynchronization::afterCommit); verify(realtimePublisher).publish(any()); } finally { org.springframework.transaction.support.TransactionSynchronizationManager.clearSynchronization(); } }
    @Test void 저장_실패로_롤백되면_Redis_전파하지_않는다(){ given(rooms.findById(3L)).willReturn(Optional.of(room())); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.RECRUITING)); given(messages.save(any())).willThrow(new IllegalStateException()); assertThatThrownBy(()->service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"안녕하세요")).isInstanceOf(IllegalStateException.class); verifyNoInteractions(realtimePublisher); }
    @Test void asyncModerationDispatcher가_주입되지_않으면_호출하지_않는다(){ ChatRoom room=room(); ChatMessage saved=ChatMessage.create(3L,7L,8L,"안녕하세요"); ReflectionTestUtils.setField(saved,"id",101L); ReflectionTestUtils.setField(saved,"createdAt",NOW); given(rooms.findById(3L)).willReturn(Optional.of(room)); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.RECRUITING)); given(messages.save(any())).willReturn(saved); given(names.readNames(any())).willReturn(Map.of(7L,"회원")); service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"안녕하세요"); }
    @Test void asyncModerationDispatcher가_주입되면_커밋후_messageId로_디스패치한다(){ com.bobfull.chat.service.ChatMessageAsyncModerationDispatcher asyncModerationDispatcher=org.mockito.Mockito.mock(com.bobfull.chat.service.ChatMessageAsyncModerationDispatcher.class); ReflectionTestUtils.setField(service,"asyncModerationDispatcher",asyncModerationDispatcher); ChatMessage saved=ChatMessage.create(3L,7L,8L,"안녕하세요"); ReflectionTestUtils.setField(saved,"id",101L); ReflectionTestUtils.setField(saved,"createdAt",NOW); given(rooms.findById(3L)).willReturn(Optional.of(room())); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.RECRUITING)); given(messages.save(any())).willReturn(saved); given(names.readNames(any())).willReturn(Map.of(7L,"회원")); org.springframework.transaction.support.TransactionSynchronizationManager.initSynchronization(); try { service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"안녕하세요"); verifyNoInteractions(asyncModerationDispatcher); org.springframework.transaction.support.TransactionSynchronizationManager.getSynchronizations().forEach(org.springframework.transaction.support.TransactionSynchronization::afterCommit); verify(asyncModerationDispatcher).dispatch(101L); } finally { org.springframework.transaction.support.TransactionSynchronizationManager.clearSynchronization(); } }
    @Test void 식사종료시각과_같거나_지나면_CONFIRMED여도_SEND를_차단한다(){ given(rooms.findById(3L)).willReturn(Optional.of(room())); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.CONFIRMED,NOW)); assertCode(() -> service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"a"),ChatErrorCode.CHAT_MESSAGE_SEND_NOT_ALLOWED); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.CONFIRMED,NOW.minusSeconds(1))); assertCode(() -> service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"a"),ChatErrorCode.CHAT_MESSAGE_SEND_NOT_ALLOWED); }
    @Test void 식사종료시각_전이면_CONFIRMED_예약은_SEND에_성공한다(){ ChatRoom room=room(); ChatMessage saved=ChatMessage.create(3L,7L,8L,"안녕"); ReflectionTestUtils.setField(saved,"id",102L); ReflectionTestUtils.setField(saved,"createdAt",NOW); given(rooms.findById(3L)).willReturn(Optional.of(room)); given(access.read(10L,7L)).willReturn(new ReservationChatAccessReader.ChatAccess(8L,ParticipationStatus.RESERVED,ReservationStatus.CONFIRMED,NOW.plusSeconds(1))); given(messages.save(any())).willReturn(saved); given(names.readNames(any())).willReturn(Map.of(7L,"회원")); var response=service.send(3L,new AuthMember(7L,MemberRole.MEMBER),"안녕"); assertThat(response).extracting("messageId").isEqualTo(102L); }
    private ChatRoom room(){ ChatRoom r=ChatRoom.create(10L);ReflectionTestUtils.setField(r,"id",3L);return r;} private void assertInvalid(String s){assertCode(()->service.send(3L,new AuthMember(7L,MemberRole.MEMBER),s),CommonErrorCode.INVALID_INPUT_VALUE);} private void assertCode(org.assertj.core.api.ThrowableAssert.ThrowingCallable c,BaseErrorCode code){assertThatThrownBy(c).isInstanceOf(CustomException.class).extracting(e->((CustomException)e).getErrorCode()).isEqualTo(code);}
}
