package com.bobfull.admin.service;
import com.bobfull.admin.dto.*; import com.bobfull.admin.repository.MemberModerationQueryRepository; import com.bobfull.chat.entity.*; import com.bobfull.chat.repository.*; import com.bobfull.common.exception.*; import com.bobfull.common.response.PageResponse; import java.time.Clock; import java.util.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
/** ADMIN의 신고 조회와 Human 최종 판단을 처리한다. 판단은 회원 제재를 변경하지 않는다. */
@Service public class AdminModerationReportService { private final ChatRoomMemberReportRepository reports; private final ChatMessageRepository messages; private final ChatModerationRepository moderations; private final MemberModerationQueryRepository memberModerations; private final Clock clock; public AdminModerationReportService(ChatRoomMemberReportRepository reports,ChatMessageRepository messages,ChatModerationRepository moderations,MemberModerationQueryRepository memberModerations,Clock clock){this.reports=reports;this.messages=messages;this.moderations=moderations;this.memberModerations=memberModerations;this.clock=clock;}
 @Transactional(readOnly=true) public PageResponse<AdminModerationReportResponse> getReports(ReportStatus status,Pageable pageable){return PageResponse.from(reports.findByStatusOrderByCreatedAtDesc(status==null?ReportStatus.PENDING:status,pageable).map(AdminModerationReportResponse::from));}
 @Transactional(readOnly=true) public AdminModerationReportDetailResponse getReportDetail(Long reportId){ChatRoomMemberReport report=reports.findById(reportId).orElseThrow(()->new CustomException(ChatErrorCode.CHAT_ROOM_REPORT_NOT_FOUND)); MemberModerationSummaryResult moderationSummary=memberModerations.findMemberSummary(report.getReportedMemberId()).orElse(new MemberModerationSummaryResult(report.getReportedMemberId(),0,0,0,0,0,null)); return new AdminModerationReportDetailResponse(report.getId(),report.getChatRoomId(),report.getReason(),report.getDetail(),report.getReporterMemberId(),report.getReportedMemberId(),report.getAnchorMessageId(),report.getCreatedAt(),report.getStatus(),getContextMessages(report),new AdminModerationReportDetailResponse.ModerationSignals(moderationSummary.totalFlaggedCount(),moderationSummary.reviewTargetCount(),moderationSummary.profanityCount(),moderationSummary.personalInformationCount(),moderationSummary.spamCount()),new AdminModerationReportDetailResponse.ReportSignals(reports.countByReportedMemberIdAndStatus(report.getReportedMemberId(),ReportStatus.PENDING),reports.countByReportedMemberIdAndStatus(report.getReportedMemberId(),ReportStatus.REVIEWED),reports.countByReportedMemberIdAndDecision(report.getReportedMemberId(),ReviewDecision.VIOLATION_CONFIRMED)));}
 @Transactional public AdminModerationReportResponse review(Long reportId,Long adminMemberId,AdminReportReviewRequest request){ChatRoomMemberReport report=reports.findById(reportId).orElseThrow(()->new CustomException(ChatErrorCode.CHAT_ROOM_REPORT_NOT_FOUND)); if(report.getStatus()!=ReportStatus.PENDING)throw new CustomException(ChatErrorCode.CHAT_ROOM_REPORT_ALREADY_REVIEWED); report.review(request.decision(),adminMemberId,clock.instant()); return AdminModerationReportResponse.from(report);}
 private List<AdminModerationReportDetailResponse.ContextMessage> getContextMessages(ChatRoomMemberReport report){List<ChatMessage> chatRoomMessages=messages.findByChatRoomIdOrderByIdAsc(report.getChatRoomId()); List<ChatMessage> contextMessages;if(report.getAnchorMessageId()!=null){int anchorMessageIndex=0;while(anchorMessageIndex<chatRoomMessages.size()&&!chatRoomMessages.get(anchorMessageIndex).getId().equals(report.getAnchorMessageId()))anchorMessageIndex++; contextMessages=chatRoomMessages.subList(Math.max(0,anchorMessageIndex-5),Math.min(chatRoomMessages.size(),anchorMessageIndex+6));}else{List<ChatMessage> messagesBeforeReport=messages.findTop20ByChatRoomIdAndCreatedAtLessThanEqualOrderByIdDesc(report.getChatRoomId(),report.getCreatedAt());Collections.reverse(messagesBeforeReport);contextMessages=messagesBeforeReport;}Map<Long,ChatModeration> moderationByMessageId=moderations.findByMessageIdIn(contextMessages.stream().map(ChatMessage::getId).toList()).stream().collect(java.util.stream.Collectors.toMap(ChatModeration::getMessageId,moderation->moderation));return contextMessages.stream().map(message->{ChatModeration moderation=moderationByMessageId.get(message.getId());return new AdminModerationReportDetailResponse.ContextMessage(message.getId(),message.getSenderMemberId(),message.getContent(),message.getCreatedAt(),moderation==null?null:new AdminModerationReportDetailResponse.Moderation(moderation.getStatus(),moderation.getCategories(),moderation.getRiskLevel(),moderation.getPromptVersion(),moderation.getPolicyVersion(),moderation.getAnalyzedAt()));}).toList();}
}
