package com.bobfull.infrastructure.outbox.entity;

public enum OutboxEventType {
    CHAT_ROOM_CREATION_REQUESTED,
    EMAIL_RESERVATION_CREATED,
    EMAIL_PARTICIPATION_COMPLETED,
    EMAIL_RECRUITMENT_CONFIRMED,
    EMAIL_RECRUITMENT_CANCELLED,
    CHAT_MESSAGE_CREATED
}
