package com.bobfull.admin.service;
import static org.assertj.core.api.Assertions.*; import static org.mockito.BDDMockito.*;
import com.bobfull.admin.dto.*; import com.bobfull.admin.repository.MemberModerationQueryRepository; import com.bobfull.chat.entity.*; import com.bobfull.chat.repository.*; import com.bobfull.common.exception.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.Test; import org.springframework.test.util.ReflectionTestUtils;
class AdminModerationReportServiceTest {
 private final ChatRoomMemberReportRepository reports=mock(ChatRoomMemberReportRepository.class); private final ChatMessageRepository messages=mock(ChatMessageRepository.class); private final ChatModerationRepository moderations=mock(ChatModerationRepository.class); private final MemberModerationQueryRepository summaries=mock(MemberModerationQueryRepository.class); private final AdminModerationReportService service=new AdminModerationReportService(reports,messages,moderations,summaries,Clock.fixed(Instant.parse("2026-08-11T00:00:00Z"),ZoneOffset.UTC));
 @Test void PENDING_신고는_Human_판단만_저장하고_REVIEWED로_전이한다(){ChatRoomMemberReport r=report();given(reports.findById(1L)).willReturn(Optional.of(r));var result=service.review(1L,99L,new AdminReportReviewRequest(ReviewDecision.VIOLATION_CONFIRMED));assertThat(result.status()).isEqualTo(ReportStatus.REVIEWED);assertThat(result.reviewedByMemberId()).isEqualTo(99L);assertThat(result.decision()).isEqualTo(ReviewDecision.VIOLATION_CONFIRMED);}
 @Test void 이미_REVIEWED면_재검토를_차단한다(){ChatRoomMemberReport r=report();r.review(ReviewDecision.NO_VIOLATION,99L,Instant.now());given(reports.findById(1L)).willReturn(Optional.of(r));assertThatThrownBy(()->service.review(1L,100L,new AdminReportReviewRequest(ReviewDecision.VIOLATION_CONFIRMED))).isInstanceOf(CustomException.class).extracting(e->((CustomException)e).getErrorCode()).isEqualTo(ChatErrorCode.CHAT_ROOM_REPORT_ALREADY_REVIEWED);}
 @Test void anchor_상세는_같은방의_정렬된_Context와_SAFE_FLAGGED_FAILED_AI결과를_매핑한다(){ChatRoomMemberReport r=ChatRoomMemberReport.create(3L,7L,8L,2L,ReportReason.ABUSE,null);ReflectionTestUtils.setField(r,"id",1L);given(reports.findById(1L)).willReturn(Optional.of(r));ChatMessage a=message(1L);ChatMessage b=message(2L);ChatMessage c=message(3L);given(messages.findByChatRoomIdOrderByIdAsc(3L)).willReturn(List.of(a,b,c));given(summaries.findMemberSummary(8L)).willReturn(Optional.of(new MemberModerationSummaryResult(8L,1,2,3,6,5,null)));ChatModeration safe=ChatModeration.completed(1L,ModerationResultType.SAFE,Set.of(),RiskLevel.LOW,"o","m","p","v",1,null,null,null,Instant.now());ChatModeration flagged=ChatModeration.completed(2L,ModerationResultType.FLAGGED,Set.of(ModerationCategory.SPAM),RiskLevel.HIGH,"o","m","p","v",1,null,null,null,Instant.now());ChatModeration failed=ChatModeration.failed(3L,"o","m","p","v",1,Instant.now(),"TIMEOUT");given(moderations.findByMessageIdIn(List.of(1L,2L,3L))).willReturn(List.of(safe,flagged,failed));var d=service.getReportDetail(1L);assertThat(d.context().stream().map(x->x.messageId())).containsExactly(1L,2L,3L);assertThat(d.context().get(0).moderation().status()).isEqualTo(ModerationProcessingStatus.SAFE);assertThat(d.context().get(1).moderation().status()).isEqualTo(ModerationProcessingStatus.FLAGGED);assertThat(d.context().get(2).moderation().status()).isEqualTo(ModerationProcessingStatus.ANALYSIS_FAILED);assertThat(d.moderationSignals().totalFlaggedCount()).isEqualTo(6);}
 @Test void anchor_없음은_신고시각_이전_동일방_최대20건과_피신고회원_누적만_반환한다(){ChatRoomMemberReport r=report();given(reports.findById(1L)).willReturn(Optional.of(r));List<ChatMessage> prior=java.util.stream.LongStream.iterate(21,n->n-1).limit(20).mapToObj(this::message).toList();given(messages.findTop20ByChatRoomIdAndCreatedAtLessThanEqualOrderByIdDesc(eq(3L),any())).willReturn(new ArrayList<>(prior));given(summaries.findMemberSummary(8L)).willReturn(Optional.empty());given(reports.countByReportedMemberIdAndStatus(8L,ReportStatus.PENDING)).willReturn(2L);given(reports.countByReportedMemberIdAndStatus(8L,ReportStatus.REVIEWED)).willReturn(3L);given(reports.countByReportedMemberIdAndDecision(8L,ReviewDecision.VIOLATION_CONFIRMED)).willReturn(1L);var d=service.getReportDetail(1L);assertThat(d.context()).hasSize(20);assertThat(d.context().get(0).messageId()).isEqualTo(2L);assertThat(d.context().get(19).messageId()).isEqualTo(21L);assertThat(d.reportSignals()).extracting("pendingReportCount","reviewedReportCount","confirmedViolationCount").containsExactly(2L,3L,1L);then(reports).should().countByReportedMemberIdAndStatus(8L,ReportStatus.PENDING);}
 private ChatRoomMemberReport report(){ChatRoomMemberReport r=ChatRoomMemberReport.create(3L,7L,8L,null,ReportReason.ABUSE,null);ReflectionTestUtils.setField(r,"id",1L);return r;}
 private ChatMessage message(Long id){ChatMessage m=ChatMessage.create(3L,8L,1L,"m"+id);ReflectionTestUtils.setField(m,"id",id);return m;}
}
